configured_endpoints: 232
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/increase%2Fincrease-1127bb6ee64bebab1bbf8ecbd9ec71c0deb5ca8552fd454fa2ec120fd9eac14a.yml
openapi_spec_hash: 9fedc9dc133202e4d39bf7bffe4839d9
config_hash: 4b562e97b3d8b4cba758a87d4927a76d
