// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package increase

import (
	"context"
	"net/http"
	"slices"

	"github.com/Increase/increase-go/internal/apijson"
	"github.com/Increase/increase-go/internal/param"
	"github.com/Increase/increase-go/internal/requestconfig"
	"github.com/Increase/increase-go/option"
)

// SimulationCardBalanceInquiryService contains methods and other services that
// help with interacting with the increase API.
//
// Note, unlike clients, this service does not read variables from the environment
// automatically. You should not instantiate this service directly, and instead use
// the [NewSimulationCardBalanceInquiryService] method instead.
type SimulationCardBalanceInquiryService struct {
	Options []option.RequestOption
}

// NewSimulationCardBalanceInquiryService generates a new service that applies the
// given options to each request. These options are applied after the parent
// client's options (if there is one), and before any request-specific options.
func NewSimulationCardBalanceInquiryService(opts ...option.RequestOption) (r *SimulationCardBalanceInquiryService) {
	r = &SimulationCardBalanceInquiryService{}
	r.Options = opts
	return
}

// Simulates a balance inquiry on a [Card](#cards).
func (r *SimulationCardBalanceInquiryService) New(ctx context.Context, body SimulationCardBalanceInquiryNewParams, opts ...option.RequestOption) (res *CardPayment, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "simulations/card_balance_inquiries"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return
}

type SimulationCardBalanceInquiryNewParams struct {
	// The balance amount in cents. The account balance will be used if not provided.
	Balance param.Field[int64] `json:"balance"`
	// The identifier of the Card to be authorized.
	CardID param.Field[string] `json:"card_id"`
	// Forces a card decline with a specific reason. No real time decision will be
	// sent.
	DeclineReason param.Field[SimulationCardBalanceInquiryNewParamsDeclineReason] `json:"decline_reason"`
	// The identifier of the Digital Wallet Token to be authorized.
	DigitalWalletTokenID param.Field[string] `json:"digital_wallet_token_id"`
	// The identifier of the Event Subscription to use. If provided, will override the
	// default real time event subscription. Because you can only create one real time
	// decision event subscription, you can use this field to route events to any
	// specified event subscription for testing purposes.
	EventSubscriptionID param.Field[string] `json:"event_subscription_id"`
	// The merchant identifier (commonly abbreviated as MID) of the merchant the card
	// is transacting with.
	MerchantAcceptorID param.Field[string] `json:"merchant_acceptor_id"`
	// The Merchant Category Code (commonly abbreviated as MCC) of the merchant the
	// card is transacting with.
	MerchantCategoryCode param.Field[string] `json:"merchant_category_code"`
	// The city the merchant resides in.
	MerchantCity param.Field[string] `json:"merchant_city"`
	// The country the merchant resides in.
	MerchantCountry param.Field[string] `json:"merchant_country"`
	// The merchant descriptor of the merchant the card is transacting with.
	MerchantDescriptor param.Field[string] `json:"merchant_descriptor"`
	// The state the merchant resides in.
	MerchantState param.Field[string] `json:"merchant_state"`
	// Fields specific to a given card network.
	NetworkDetails param.Field[SimulationCardBalanceInquiryNewParamsNetworkDetails] `json:"network_details"`
	// The risk score generated by the card network. For Visa this is the Visa Advanced
	// Authorization risk score, from 0 to 99, where 99 is the riskiest.
	NetworkRiskScore param.Field[int64] `json:"network_risk_score"`
	// The identifier of the Physical Card to be authorized.
	PhysicalCardID param.Field[string] `json:"physical_card_id"`
	// The terminal identifier (commonly abbreviated as TID) of the terminal the card
	// is transacting with.
	TerminalID param.Field[string] `json:"terminal_id"`
}

func (r SimulationCardBalanceInquiryNewParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

// Forces a card decline with a specific reason. No real time decision will be
// sent.
type SimulationCardBalanceInquiryNewParamsDeclineReason string

const (
	SimulationCardBalanceInquiryNewParamsDeclineReasonAccountClosed                SimulationCardBalanceInquiryNewParamsDeclineReason = "account_closed"
	SimulationCardBalanceInquiryNewParamsDeclineReasonCardNotActive                SimulationCardBalanceInquiryNewParamsDeclineReason = "card_not_active"
	SimulationCardBalanceInquiryNewParamsDeclineReasonCardCanceled                 SimulationCardBalanceInquiryNewParamsDeclineReason = "card_canceled"
	SimulationCardBalanceInquiryNewParamsDeclineReasonPhysicalCardNotActive        SimulationCardBalanceInquiryNewParamsDeclineReason = "physical_card_not_active"
	SimulationCardBalanceInquiryNewParamsDeclineReasonEntityNotActive              SimulationCardBalanceInquiryNewParamsDeclineReason = "entity_not_active"
	SimulationCardBalanceInquiryNewParamsDeclineReasonGroupLocked                  SimulationCardBalanceInquiryNewParamsDeclineReason = "group_locked"
	SimulationCardBalanceInquiryNewParamsDeclineReasonInsufficientFunds            SimulationCardBalanceInquiryNewParamsDeclineReason = "insufficient_funds"
	SimulationCardBalanceInquiryNewParamsDeclineReasonCvv2Mismatch                 SimulationCardBalanceInquiryNewParamsDeclineReason = "cvv2_mismatch"
	SimulationCardBalanceInquiryNewParamsDeclineReasonPinMismatch                  SimulationCardBalanceInquiryNewParamsDeclineReason = "pin_mismatch"
	SimulationCardBalanceInquiryNewParamsDeclineReasonCardExpirationMismatch       SimulationCardBalanceInquiryNewParamsDeclineReason = "card_expiration_mismatch"
	SimulationCardBalanceInquiryNewParamsDeclineReasonTransactionNotAllowed        SimulationCardBalanceInquiryNewParamsDeclineReason = "transaction_not_allowed"
	SimulationCardBalanceInquiryNewParamsDeclineReasonBreachesLimit                SimulationCardBalanceInquiryNewParamsDeclineReason = "breaches_limit"
	SimulationCardBalanceInquiryNewParamsDeclineReasonWebhookDeclined              SimulationCardBalanceInquiryNewParamsDeclineReason = "webhook_declined"
	SimulationCardBalanceInquiryNewParamsDeclineReasonWebhookTimedOut              SimulationCardBalanceInquiryNewParamsDeclineReason = "webhook_timed_out"
	SimulationCardBalanceInquiryNewParamsDeclineReasonDeclinedByStandInProcessing  SimulationCardBalanceInquiryNewParamsDeclineReason = "declined_by_stand_in_processing"
	SimulationCardBalanceInquiryNewParamsDeclineReasonInvalidPhysicalCard          SimulationCardBalanceInquiryNewParamsDeclineReason = "invalid_physical_card"
	SimulationCardBalanceInquiryNewParamsDeclineReasonMissingOriginalAuthorization SimulationCardBalanceInquiryNewParamsDeclineReason = "missing_original_authorization"
	SimulationCardBalanceInquiryNewParamsDeclineReasonFailed3DSAuthentication      SimulationCardBalanceInquiryNewParamsDeclineReason = "failed_3ds_authentication"
	SimulationCardBalanceInquiryNewParamsDeclineReasonSuspectedCardTesting         SimulationCardBalanceInquiryNewParamsDeclineReason = "suspected_card_testing"
	SimulationCardBalanceInquiryNewParamsDeclineReasonSuspectedFraud               SimulationCardBalanceInquiryNewParamsDeclineReason = "suspected_fraud"
)

func (r SimulationCardBalanceInquiryNewParamsDeclineReason) IsKnown() bool {
	switch r {
	case SimulationCardBalanceInquiryNewParamsDeclineReasonAccountClosed, SimulationCardBalanceInquiryNewParamsDeclineReasonCardNotActive, SimulationCardBalanceInquiryNewParamsDeclineReasonCardCanceled, SimulationCardBalanceInquiryNewParamsDeclineReasonPhysicalCardNotActive, SimulationCardBalanceInquiryNewParamsDeclineReasonEntityNotActive, SimulationCardBalanceInquiryNewParamsDeclineReasonGroupLocked, SimulationCardBalanceInquiryNewParamsDeclineReasonInsufficientFunds, SimulationCardBalanceInquiryNewParamsDeclineReasonCvv2Mismatch, SimulationCardBalanceInquiryNewParamsDeclineReasonPinMismatch, SimulationCardBalanceInquiryNewParamsDeclineReasonCardExpirationMismatch, SimulationCardBalanceInquiryNewParamsDeclineReasonTransactionNotAllowed, SimulationCardBalanceInquiryNewParamsDeclineReasonBreachesLimit, SimulationCardBalanceInquiryNewParamsDeclineReasonWebhookDeclined, SimulationCardBalanceInquiryNewParamsDeclineReasonWebhookTimedOut, SimulationCardBalanceInquiryNewParamsDeclineReasonDeclinedByStandInProcessing, SimulationCardBalanceInquiryNewParamsDeclineReasonInvalidPhysicalCard, SimulationCardBalanceInquiryNewParamsDeclineReasonMissingOriginalAuthorization, SimulationCardBalanceInquiryNewParamsDeclineReasonFailed3DSAuthentication, SimulationCardBalanceInquiryNewParamsDeclineReasonSuspectedCardTesting, SimulationCardBalanceInquiryNewParamsDeclineReasonSuspectedFraud:
		return true
	}
	return false
}

// Fields specific to a given card network.
type SimulationCardBalanceInquiryNewParamsNetworkDetails struct {
	// Fields specific to the Visa network.
	Visa param.Field[SimulationCardBalanceInquiryNewParamsNetworkDetailsVisa] `json:"visa,required"`
}

func (r SimulationCardBalanceInquiryNewParamsNetworkDetails) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

// Fields specific to the Visa network.
type SimulationCardBalanceInquiryNewParamsNetworkDetailsVisa struct {
	// The reason code for the stand-in processing.
	StandInProcessingReason param.Field[SimulationCardBalanceInquiryNewParamsNetworkDetailsVisaStandInProcessingReason] `json:"stand_in_processing_reason"`
}

func (r SimulationCardBalanceInquiryNewParamsNetworkDetailsVisa) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

// The reason code for the stand-in processing.
type SimulationCardBalanceInquiryNewParamsNetworkDetailsVisaStandInProcessingReason string

const (
	SimulationCardBalanceInquiryNewParamsNetworkDetailsVisaStandInProcessingReasonIssuerError                                              SimulationCardBalanceInquiryNewParamsNetworkDetailsVisaStandInProcessingReason = "issuer_error"
	SimulationCardBalanceInquiryNewParamsNetworkDetailsVisaStandInProcessingReasonInvalidPhysicalCard                                      SimulationCardBalanceInquiryNewParamsNetworkDetailsVisaStandInProcessingReason = "invalid_physical_card"
	SimulationCardBalanceInquiryNewParamsNetworkDetailsVisaStandInProcessingReasonInvalidCardholderAuthenticationVerificationValue         SimulationCardBalanceInquiryNewParamsNetworkDetailsVisaStandInProcessingReason = "invalid_cardholder_authentication_verification_value"
	SimulationCardBalanceInquiryNewParamsNetworkDetailsVisaStandInProcessingReasonInternalVisaError                                        SimulationCardBalanceInquiryNewParamsNetworkDetailsVisaStandInProcessingReason = "internal_visa_error"
	SimulationCardBalanceInquiryNewParamsNetworkDetailsVisaStandInProcessingReasonMerchantTransactionAdvisoryServiceAuthenticationRequired SimulationCardBalanceInquiryNewParamsNetworkDetailsVisaStandInProcessingReason = "merchant_transaction_advisory_service_authentication_required"
	SimulationCardBalanceInquiryNewParamsNetworkDetailsVisaStandInProcessingReasonPaymentFraudDisruptionAcquirerBlock                      SimulationCardBalanceInquiryNewParamsNetworkDetailsVisaStandInProcessingReason = "payment_fraud_disruption_acquirer_block"
	SimulationCardBalanceInquiryNewParamsNetworkDetailsVisaStandInProcessingReasonOther                                                    SimulationCardBalanceInquiryNewParamsNetworkDetailsVisaStandInProcessingReason = "other"
)

func (r SimulationCardBalanceInquiryNewParamsNetworkDetailsVisaStandInProcessingReason) IsKnown() bool {
	switch r {
	case SimulationCardBalanceInquiryNewParamsNetworkDetailsVisaStandInProcessingReasonIssuerError, SimulationCardBalanceInquiryNewParamsNetworkDetailsVisaStandInProcessingReasonInvalidPhysicalCard, SimulationCardBalanceInquiryNewParamsNetworkDetailsVisaStandInProcessingReasonInvalidCardholderAuthenticationVerificationValue, SimulationCardBalanceInquiryNewParamsNetworkDetailsVisaStandInProcessingReasonInternalVisaError, SimulationCardBalanceInquiryNewParamsNetworkDetailsVisaStandInProcessingReasonMerchantTransactionAdvisoryServiceAuthenticationRequired, SimulationCardBalanceInquiryNewParamsNetworkDetailsVisaStandInProcessingReasonPaymentFraudDisruptionAcquirerBlock, SimulationCardBalanceInquiryNewParamsNetworkDetailsVisaStandInProcessingReasonOther:
		return true
	}
	return false
}
