package files

type File struct {
	// The time the File was created.
	CreatedAt *string `json:"created_at,omitempty"`

	// The File's identifier.
	Id *string `json:"id,omitempty"`

	// What the File will be used for. We may add additional possible values for this
	// enum over time; your application should be able to handle such additions
	// gracefully.
	Purpose *string `json:"purpose,omitempty"`

	// A description of the File.
	Description *string `json:"description,omitempty"`

	// Whether the File was generated by Increase or by you and sent to Increase.
	Direction *string `json:"direction,omitempty"`

	// The filename that was provided upon upload or generated by Increase.
	Filename *string `json:"filename,omitempty"`

	// A URL from where the File can be downloaded at this point in time. The location
	// of this URL may change over time.
	DownloadURL *string `json:"download_url,omitempty"`

	// A constant representing the object's type. For this resource it will always be
	// `file`.
	Type *string `json:"type,omitempty"`
}

// The time the File was created.
func (r *File) GetCreatedAt() (CreatedAt string) {
	if r != nil && r.CreatedAt != nil {
		CreatedAt = *r.CreatedAt
	}
	return
}

// The File's identifier.
func (r *File) GetId() (Id string) {
	if r != nil && r.Id != nil {
		Id = *r.Id
	}
	return
}

// What the File will be used for. We may add additional possible values for this
// enum over time; your application should be able to handle such additions
// gracefully.
func (r *File) GetPurpose() (Purpose string) {
	if r != nil && r.Purpose != nil {
		Purpose = *r.Purpose
	}
	return
}

// A description of the File.
func (r *File) GetDescription() (Description string) {
	if r != nil && r.Description != nil {
		Description = *r.Description
	}
	return
}

// Whether the File was generated by Increase or by you and sent to Increase.
func (r *File) GetDirection() (Direction string) {
	if r != nil && r.Direction != nil {
		Direction = *r.Direction
	}
	return
}

// The filename that was provided upon upload or generated by Increase.
func (r *File) GetFilename() (Filename string) {
	if r != nil && r.Filename != nil {
		Filename = *r.Filename
	}
	return
}

// A URL from where the File can be downloaded at this point in time. The location
// of this URL may change over time.
func (r *File) GetDownloadURL() (DownloadURL string) {
	if r != nil && r.DownloadURL != nil {
		DownloadURL = *r.DownloadURL
	}
	return
}

// A constant representing the object's type. For this resource it will always be
// `file`.
func (r *File) GetType() (Type string) {
	if r != nil && r.Type != nil {
		Type = *r.Type
	}
	return
}
