name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    timeout-minutes: 10
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: ./go.mod

      - name: Run lints
        run: ./scripts/lint

      - name: Build
        run: go build ./...

      - name: Bootstrap
        run: ./scripts/bootstrap

      - name: Run tests
        run: ./scripts/test
